<?php

/**
 * This is the model base class for the table "fan_genres".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "FanGenres".
 *
 * Columns in table "fan_genres" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $fan_id
 * @property integer $genre_id
 *
 */
abstract class BaseFanGenres extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'fan_genres';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'FanGenres|FanGenres', $n);
	}

	public static function representingColumn() {
		return array(
			'fan_id',
			'genre_id',
		);
	}

	public function rules() {
		return array(
			array('fan_id, genre_id', 'required'),
			array('fan_id, genre_id', 'numerical', 'integerOnly'=>true),
			array('fan_id, genre_id', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'fan_id' => null,
			'genre_id' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('fan_id', $this->fan_id);
		$criteria->compare('genre_id', $this->genre_id);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}