<?php

/**
 * This is the model base class for the table "genres".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Genres".
 *
 * Columns in table "genres" available as properties of the model,
 * followed by relations of table "genres" available as properties of the model.
 *
 * @property integer $id
 * @property string $name
 *
 * @property Artists[] $artists
 * @property Fans[] $fans
 */
abstract class BaseGenres extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'genres';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Genres|Genres', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name', 'required'),
			array('name', 'length', 'max'=>50),
			array('id, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'artists' => array(self::MANY_MANY, 'Artists', 'artist_genres(genre_id, artist_id)'),
			'fans' => array(self::MANY_MANY, 'Fans', 'fan_genres(genre_id, fan_id)'),
		);
	}

	public function pivotModels() {
		return array(
			'artists' => 'ArtistGenres',
			'fans' => 'FanGenres',
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'name' => Yii::t('app', 'Name'),
			'artists' => null,
			'fans' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}